# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2020-05-02 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Today', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Today',
            new_name='Event',
        ),
    ]
